name: flutter_puzzle_challenge
description: Creating a new version of the sliding puzzle game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+9
  just_audio: ^0.9.20
  just_audio_libwinmedia: ^0.0.4
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/music/
