name: circluzzle
description: Creating a new version of the sliding puzzle game
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+9
  just_audio: ^0.9.20
  just_audio_libwinmedia: ^0.0.4
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/music/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

msix_config:
  display_name: Circluzzle
  publisher_display_name: WiVe
  identity_name: 7326WiVe.Circluzzle
  msix_version: 1.0.0.0
  logo_path: C:\Git\circluzzle\assets\icon.png
  start_menu_icon_path: C:\Git\circluzzle\assets\icon.png
  tile_icon_path: C:\Git\circluzzle\assets\icon.png
  store: true
  publisher: CN=C55C8308-FC6E-4821-842A-211727F3AEFE
